### ISSUE TITLE
Using 'dispatch' package name on PyPI

### ISSUE THREAD

**Issue by psiemens** [iwillig/dispatch#1]
Hey @iwillig --

I noticed that you are the owner of https://pypi.python.org/pypi/dispatch. This might seem like a strange request, but I was wondering if you would be willing to transfer the package ownership to my PyPI account so that I can make use of the name `dispatch`. Normally I wouldn't bother you, but it looks like you've stopped developing the package and probably wouldn't mind letting it go.

I'm hoping to use the name for https://github.com/ubyssey/dispatch, a Django-powered publishing platform being used and developed by several student journalists. We've been building it for over a year and are finally ready to upload it to PyPI -- we just need the name :)

Many thanks,

Peter

**Comment by iwillig** [comment]
Of course,

I _think_ i just renamed that package. Can you try creating it now?



Ivan Willig

**Comment by psiemens** [comment]
Thanks! I just tried to upload it, but it's still showing me this:

`Server response (403): You are not allowed to store 'dispatch' package information`

I _think_ you have to make me an owner of the package so that I can overwrite it. My PyPI username is "psiemens"

**Comment by iwillig** [comment]
Hey I just removed it from pypi

Can you create a package now?

Ivan Willig

**Comment by psiemens** [comment]
It worked! Thanks so much. Sending a virtual  :beer: your way.
